Add a banner to display a disclaimer
MystenLabs/solitaire pull request #40
Opened 2024-06-19 10:06 UTC by nonvis

2024-06-26 07:53 UTC, Tzal3x requested changes
Hello! Nice work 👍 
Two fixes: 
- typo on banner text
- white space on landing screen layout (see vercel deployment comment)

2024-06-26 07:53 UTC, Tzal3x commented on app/src/app/ProvidersAndLayout.tsx
> +            <span className="text-opacity-90 text-[14px] text-[#4F4F4F]">[Mysten Solitaire] is provided for testnet purposes only and do not involve real money or the opportunity to win real money.</
```suggestion
            <span className="text-opacity-90 text-[14px] text-[#4F4F4F]">[Mysten Solitaire] is provided for testnet purposes only and does not involve real money or the opportunity to win real money.</span>
```

2024-06-26 15:30 UTC, nonvis commented on app/src/app/ProvidersAndLayout.tsx
> +            <span className="text-opacity-90 text-[14px] text-[#4F4F4F]">[Mysten Solitaire] is provided for testnet purposes only and do not involve real money or the opportunity to win real money.</
I've fixed the typo.

2024-06-27 07:05 UTC, Tzal3x approved these changes
Awesome, let's merge!

2024-06-27 08:37 UTC, merged